Repository TtoGal/backend, pull requests merged in 2024-12, with the labels that each got.

#8 [feat] 유저 dto 및 엔티티 구현
  backend/src/main/java/com/ttogal/api/controller/user/UserController.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/request/UserRegisterRequestDto.java
  backend/src/main/java/com/ttogal/api/service/user/UserService.java
  backend/src/main/java/com/ttogal/common/auth/email/EmailController.java
  backend/src/main/java/com/ttogal/domain/user/entity/User.java
  backend/src/main/java/com/ttogal/domain/user/entity/constant/Gender.java
  backend/src/main/java/com/ttogal/domain/user/entity/constant/JobStatus.java
  backend/src/main/java/com/ttogal/domain/user/entity/constant/UserStatus.java
  backend/src/main/java/com/ttogal/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#13 [Chore] UserController builder 부분 -> handler 처리
  backend/src/main/java/com/ttogal/api/controller/user/UserController.java
  backend/src/main/java/com/ttogal/common/handler/user/UserResponseHandler.java
Labels: ⚙️ Config Update

#11 Update README.md
  README.md
Labels: 📃 Docs

#21 [Chore] gradlew 관련 .ignore에서 삭제
  .gitignore
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
Labels: ⚙️ Config Update

#23 [Chore] .gitignore에서 !gradle-wrapper.jar 추가
  .gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/src/main/resources/application.yaml
Labels: ⚙️ Config Update

#25 [feat] 스프링 시큐리티+JWT를 이용한 로그인 로직 구현
  backend/src/main/java/com/ttogal/api/controller/user/UserController.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/request/LoginRequestDto.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/request/UserRegisterRequestDto.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/request/ValidateEmailRequestDto.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/response/CustomUserDetails.java
  backend/src/main/java/com/ttogal/api/service/user/CustomUserDetailsService.java
  backend/src/main/java/com/ttogal/common/config/SecurityConfig.java
  backend/src/main/java/com/ttogal/common/filter/LoginFilter.java
  backend/src/main/java/com/ttogal/domain/user/entity/User.java
  backend/src/main/java/com/ttogal/domain/user/entity/constant/Role.java
  backend/src/main/java/com/ttogal/domain/user/repository/UserRepository.java
  backend/src/test/java/com/ttogal/BackendApplicationTests.java
Labels: 📬 API

#27 [feat] JWT 발급 및 검증 클래스 개발
  backend/build.gradle
  backend/src/main/java/com/ttogal/api/controller/user/UserController.java
  backend/src/main/java/com/ttogal/api/controller/user/dto/response/CustomUserDetails.java
  backend/src/main/java/com/ttogal/common/config/SecurityConfig.java
  backend/src/main/java/com/ttogal/common/filter/JwtFilter.java
  backend/src/main/java/com/ttogal/common/filter/LoginFilter.java
  backend/src/main/java/com/ttogal/common/util/JwtUtil.java
Labels: 📬 API
